settings:
  title: 'DIMO Status Page'
  url: 'https://status.dimo.zone' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:

  - id: dimo.zone
    name: dimo.zone
    description: DIMO Home Page.'
    url: 'https://dimo.zone'
    method: GET
    expectStatus: 200 
    
  - id: app
    name: DIMO App
    description: DIMO Web Application.'
    url: 'https://app.dimo.zone'
    method: GET
    expectStatus: 200 

  - id: users-api
    name: Users API
    description: API for user profiles and information.'
    url: 'https://users-api.dev.dimo.zone'
    method: GET
    expectStatus: 200 

  - id: dex
    name: Authentication API
    description: 'API for authentication to DIMO platform.'
    url: 'http://auth.dimo.zone/.well-known/openid-configuration/'
    method: GET
    expectStatus: 200

  - id: Devices API
    name: Devices API
    description: 'API for managing and adding devices.'
    url: 'https://devices-api.dimo.zone/'
    method: GET
    expectStatus: 200
